### ISSUE TITLE
Bug: In Pages - as3cf-filter.php - must be of type array

### ISSUE THREAD

**Issue by latechua** [deliciousbrains/wp-amazon-s3-and-cloudfront#609]
**Describe the bug**
**WordPress version**: [6.0.1-debian-11-r7](https://hub.docker.com/layers/wordpress/bitnami/wordpress/6.0.1-debian-11-r7/images/sha256-67338807073d314acb24462c41348ee70387e27cac6679d51b1d3d0a3207aec1?context=explore)
**Plugin version**: 1.1.2

In the admin panel in the "Pages" section, not all pages are displayed (for example, it says - navigation 21 items - but only 4 are displayed) and it says - "There has been a critical error on this website".

There is an error in the logs and a mention with wp-amazon-s3-and-cloudfront:

```
[php:error] PHP Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, string given in /bitnami/wordpress/wp-content/plugins/amazon-s3-and-cloudfront -pro/classes/as3cf-filter.php:872

Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/as3cf-filter.php(872): array_keys()

#1 /bitnami/wordpress/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/as3cf-filter.php(692): AS3CF_Filter::merge_cache()

#2 /bitnami/wordpress/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/filters/as3cf-local-to-s3.php(107): AS3CF_Filter->maybe_update_post_cache()

#3 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(309): AS3CF_Local_To_S3->filter_content_pagination()

#4 /opt/bitnami/wordpress/wp-includes/plugin.php(191): WP_Hook->apply_filters()

#5 /opt/bitnami/wordpress/wp-includes/class-wp-query.php(4543): apply_filters()

#6 /opt/bitnami/wordpress/wp-includes/class-wp-query.php(4440): WP_Query->generate_postdata()

#7 /opt/bitnami/wordpress/wp-includes/query.php(1179): WP_Query->setup_postdata()

#8 /opt/bitnami/wordpress/wp-admin/includes/class-wp-posts-list-table.php(1365): setup_postdata()

#9 /opt/bitnami/wordpress/wp-admin/includes/class-wp-posts-list-table.php(895): WP_Posts_List_Table->single_row()

#10 /opt/bitnami/wordpress/wp-admin/includes/class-wp-posts-list-table.php(770): WP_Posts_List_Table->_display_rows_hierarchical()

#11 /opt/bitnami/wordpress/wp-admin/includes/class-wp-list-table.php(1362): WP_Posts_List_Table->display_rows()

#12 /opt/bitnami/wordpress/wp-admin/includes/class-wp-list-table.php(1289): WP_List_Table->display_rows_or_placeholder()

#13 /opt/bitnami/wordpress/wp-admin/edit.php(477): WP_List_Table->display()

#14 {main}\n thrown in /bitnami/wordpress/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/as3cf-filter.php on line 872, referer: https://<site_name> .com/wp-admin/edit.php?post_type=page
```

**Screenshots**
<img width="1336" alt="Screenshot" src="https://user-images.githubusercontent.com/110596600/182802163-001179b2-0aa7-4791-973c-77928f364987.png">

**Comment by ianmjones** [comment]
Please can we see Diagnostic Info from WP Offload Media's "Support" tab?
